# Generated by Django 5.1.5 on 2025-02-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaldev_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio_projects',
            name='services',
        ),
        migrations.RemoveField(
            model_name='portfolio_projects',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='portfolio_projects',
            name='software_skills',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='portfolio_projects',
            name='technology_stack',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='portfolio_projects',
            name='industry',
            field=models.JSONField(default=list),
        ),
    ]
