# Generated by Django 5.1.5 on 2025-02-03 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaldev_backend', '0002_remove_portfolio_projects_services_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio_projects',
            old_name='software_skills',
            new_name='services',
        ),
    ]
