# Generated by Django 5.1.5 on 2025-02-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaldev_backend', '0003_rename_software_skills_portfolio_projects_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio_images',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolio_images',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
